language: node_js

node_js:
- node

dist: bionic
sudo: required

branches:
    only:
    - release

before_script:
- npm install 

deploy:
    provider: heroku
    api_key: process.env.HEROKU_KEY
    app: process.env.your_heroku_app
    on: 
        branch: release