language: node_js

node_js:
- node

dist: bionic
sudo: required

branches:
    only:
    - release

before_script:
- npm install 

deploy:
    provider: heroku
    api_key: $HEROKU_KEY
    app: cryptic-retreat-48217
    on: 
        branch: release